model: 
  name: "ppr_mbfn" 
  pretrained: "./model/mbfn_impre_aaai1v1mpd_aux_geov2_20230529_121411/020.ckpt"
data:
  name: "self_define"
  train_list: "/mnt/datasets/combine/imglists/imglist_1v1_train_rawalign.txt"
  test_list: "/mnt/datasets/combine/imglists/imglist_1v1_test_rawalign.txt"
  transform_type: "classic_transform_with_overcrop"

train:
  batch_size: 128
  gpus: [4, 5, 6, 7]
  save_freq: 1
  test_freq: 1
  optim:
    lr_start: 0.01 
    steps: [26, 36, 45]
    total_epoch: 50



